# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: languagetool 1.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "languagetool"
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Daniel Herzog"]
  s.date = "2017-05-29"
  s.description = "Gem wrapper for the LanguageTool API (public or private). It allows to correct texts."
  s.email = "info@danielherzog.es"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "languagetool.gemspec",
    "lib/languagetool.rb",
    "lib/languagetool/actions/base.rb",
    "lib/languagetool/actions/check.rb",
    "lib/languagetool/actions/languages.rb",
    "lib/languagetool/api.rb",
    "lib/languagetool/api_error.rb",
    "lib/languagetool/resources/context.rb",
    "lib/languagetool/resources/language.rb",
    "lib/languagetool/resources/languages.rb",
    "lib/languagetool/resources/match.rb",
    "lib/languagetool/resources/matches.rb",
    "lib/languagetool/resources/rule.rb",
    "lib/languagetool/resources/rule_category.rb",
    "lib/languagetool/resources/software.rb",
    "test/fixtures/vcr_cassettes/check.yml",
    "test/fixtures/vcr_cassettes/languages.yml",
    "test/helper.rb",
    "test/test_check.rb",
    "test/test_languages.rb"
  ]
  s.homepage = "https://github.com/wikiti/languagetool-ruby"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Gem wrapper for the LanguageTool API (public or private)"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rest-client>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<juwelier>, ["~> 2.0.1"])
    else
      s.add_dependency(%q<rest-client>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<juwelier>, ["~> 2.0.1"])
    end
  else
    s.add_dependency(%q<rest-client>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<juwelier>, ["~> 2.0.1"])
  end
end

